### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by lucacome** [nginxinc/nginx-prometheus-exporter#776]
```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/nginx-prometheus-exporter/issues/785
- [ ] https://github.com/nginxinc/nginx-prometheus-exporter/pull/780
- [ ] https://github.com/nginxinc/nginx-prometheus-exporter/pull/781
- [ ] https://github.com/nginxinc/nginx-prometheus-exporter/pull/782
```

**Comment by lucacome** [comment]
https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v1.3.0 was released
